using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CombosDePelea : MonoBehaviour
{
    // Propiedad pública
    // Start is called before the first frame update
    void Start()
    {

    }

    public bool IsMagicMode => isMagicMode;

    // Estado interno
    private bool isMagicMode;

    void Update()
    {
        Attack();
    }

    public void Attack()
    {
        if (isMagicMode)
            MagicAttack();
        else
            PhysicalAttack();
    }

    private void PhysicalAttack()
    {
        // Lógica de ataque físico
    }

    private void MagicAttack()
    {
        // Lógica de ataque mágico
    }


    /*
     * 
     AccionesJugador
     bool isMagicMode

     + void Update()
+ void Attack()
- void PhysicalAttack()
- void MagicAttack()
+ Update()
+ Attack()
+ PhysicalAttack
+ MagicAttack
+ IsMagicMode : bool
     */


}
